# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField()),
                ('date_updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_name', models.CharField(max_length=255)),
                ('slide_type', models.CharField(choices=[('URLI', 'URL to Image'), ('URLP', 'URL to Page'), ('HSTI', 'Hosted Image'), ('HSTP', 'Hosted Page')], max_length=4)),
                ('slide_url', models.URLField()),
                ('slide_data', models.TextField()),
                ('timing', models.PositiveIntegerField(default=5000)),
                ('displays', models.ManyToManyField(to='display.Display')),
            ],
        ),
    ]
