# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='slide_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slide',
            name='slide_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
