# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_auto_20160524_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='displays',
        ),
        migrations.AddField(
            model_name='display',
            name='slides',
            field=models.ManyToManyField(to='display.Slide'),
        ),
    ]
