# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0003_auto_20160524_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='slide_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='display',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
