# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-23 20:41
from __future__ import unicode_literals

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0008_auto_20160525_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='background_color',
            field=colorful.fields.RGBColorField(blank=True, null=True),
        ),
    ]
