# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0004_auto_20160525_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='live_load',
            field=models.BooleanField(default=False),
        ),
    ]
