# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 15:48
from __future__ import unicode_literals

from django.db import migrations
import sortedm2m.fields
from sortedm2m.operations import AlterSortedManyToManyField


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0006_slide_caption'),
    ]

    operations = [
        AlterSortedManyToManyField(
            model_name='display',
            name='slides',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, to='display.Slide'),
        ),
    ]
