# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 16:18
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0007_auto_20160525_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='caption',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
