# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0009_slide_background_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='display',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
